services:
  mongodb:
    image: mongo:7.0
    container_name: filesharing-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: filesharing
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
